name: API Gateway

on:
  pull_request:
    paths:
      - apig/**
      - test/aws_apig_test.go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
#     uses: ./.github/workflows/test_workflow.yml
#     with:
#       testArgs: -run=TestAPIG
