name: build-docker-images

on:
  pull_request:
    paths:
    - docker_images/**

defaults:
  run:
    shell: bash
    working-directory: docker_images

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["docker_images/**"]'

      - uses: actions/checkout@v2
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}

      - uses: docker/login-action@v1
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: make build
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
