name: build-docker-images

on:
  workflow_dispatch:

  pull_request:
    paths:
    - docker_images/**
    - .github/workflows/build_docker_images.yml

  push:
    branches:
      - main
    paths:
    - docker_images/**
    - .github/workflows/build_docker_images.yml

defaults:
  run:
    shell: bash
    working-directory: docker_images

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["docker_images/**"]'

      - uses: actions/checkout@v2
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}

      - uses: docker/login-action@v1
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: make build
        if: ${{ steps.skip_check.outputs.should_skip != 'true' || github.ref == 'refs/heads/master' }}

      - run: make push
        if: github.ref == 'refs/heads/master'

